### ISSUE TITLE
Stop using a timestamp as version

### ISSUE THREAD

**Issue by nox** [servo/skia#114]
We can only do patch bumps now from 0.timestamp.x to 0.timestamp.(x+1), which means we can't do incompatible bumps and this will bite us sooner or later.

**Comment by Ms2ger** [comment]
I say we just bump to 1.0.0 and go from there.

**Comment by nox** [comment]
Sounds ok to me.

**Comment by nickrobson** [comment]
So... were you going to do this?

**Comment by nox** [comment]
This was actually done, which is why the current version is 0.30000008.0.
