### ISSUE TITLE
Android 8.1 crash

### ISSUE THREAD

**Issue by MerlinYu** [servo/skia#166]
My application sometimes crash at Android 8.1.I don't know how to solve it .
Please help me find the reason and solve it .
SIGSEGV(SEGV_MAPERR):
#00 pc 0001920c /system/lib/libc.so (memset 48) [armeabi-v8::b26e7f9f9f4129427483fe26a1b6703c]
#01 pc 003a437f /system/lib/libskia.so (SkColorShader::ColorShaderContext::shadeSpanAlpha(int, int, unsigned char*, int) 10) [armeabi-v8::747df5edf75f8d7aa8e3af16e5066cfd]
#02 pc 00151395 /system/lib/libskia.so [armeabi-v8::747df5edf75f8d7aa8e3af16e5066cfd]
#03 pc 003a7b09 /system/lib/libskia.so (SkPDFDocument::reset() 68) [armeabi-v8::747df5edf75f8d7aa8e3af16e5066cfd]
#04 pc 002831b1 /system/framework/arm/boot-core-libart.oat (oatexec 1774001) [armeabi::3ccdbbb87c1d261f410748cd6955b94b]
java:
libcore.util.NativeAllocationRegistry$CleanerThunk.run(NativeAllocationRegistry.java:194)
sun.misc.Cleaner.clean(Cleaner.java:143)
java.lang.ref.ReferenceQueue.enqueueLocked(ReferenceQueue.java:75)
java.lang.ref.ReferenceQueue.enqueuePending(ReferenceQueue.java:243)
java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:193)
java.lang.Daemons$Daemon.run(Daemons.java:108)
java.lang.Thread.run(Thread.java:764)

**Comment by emilio** [comment]
This should probably be reported upstream, you don't seem to use the rust bindings that this crate provides.

You can file an skia bug in https://bugs.chromium.org/p/skia/issues/entry
