### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by LinusU** [servo/skia#70]
I'm trying to use this library but it seems like it isn't published to [cargo](https://crates.io/). There is however another package called `skia` but that is just a placeholder for someone else's project. I don't know what the policy for sitting on names is in cargo, but it would be very nice if that name could be given to an active project.

Whatever the name is thought it would be nice if this module could be published :)

**Comment by jdm** [comment]
I suspect the main thing preventing us from publishing this on cargo right now is how many dependencies would also need to be published on cargo.

**Comment by Manishearth** [comment]
I think there was an issue with publishing this library directly since crates.io has some upper limit on crate size?

**Comment by LinusU** [comment]
So, can I ask how you guys are using it currently? I'm quite new to Rust and I'm trying to just draw some simple things to a canvas and dump the pixels. Just experimenting :)

**Comment by mrobinson** [comment]
@LinusU We currently only use it through [rust-azure](https://github.com/servo/rust-azure). The basic procedure is that you create an Azure DrawTarget by calling ```DrawTarget::new(BackendType::Skia, size, SurfaceFormat::B8G8R8A8)```, paint to it calling methods like [```stroke_line```](https://github.com/servo/rust-azure/blob/master/src/azure_hl.rs#L601), and finally extract the raw image data:

```
draw_target.snapshot().get_data_surface().with_data(|data| {
    ...
}
```

**Comment by jdm** [comment]
@LinusU If you're asking how we make use of this crate with cargo, we use a direct git dependency rather than a crates.io one: https://github.com/servo/rust-layers/blob/master/Cargo.toml#L14

**Comment by LinusU** [comment]
That's cool, I'm hoping to get some more time with this :)

I'll try out the git dependency for now!

**Comment by SimonSapin** [comment]
Following up on https://github.com/servo/servo/issues/7687 and https://github.com/servo/skia/pull/73, I think we should have Servo get this crate from crates.io. To get there, we need to:

* Publish dependencies:
  * [x] euclid
  * [X] gleam
  * [X] libc
  * [ ] expat-sys
  * [ ] fontconfig (name is already used by https://github.com/cybergeek94/fontconfig-rs, I don’t know if we can or should switch to that)
  * [ ] freetype-sys (same, https://github.com/PistonDevelopers/freetype-sys.git)
  * [ ] egl (same, https://github.com/seankerr/rust-egl)
  * [ ] glx
  * [x] x11
  * [x] cgl
  * [x] io-surface
* [ ] Update skia’s `Cargo.toml` file
* [ ] Publish it
* [ ] Update Servo’s `Cargo.toml` files

**Comment by SimonSapin** [comment]
For names already used, if we can’t unify, we can publish with a `servo-` prefix (for ad-hoc namespacing) in the package name (`[package]` section in `Cargo.toml`, used for crates.io and in dependents’ `Cargo.toml` files) and still keep the unprefixed crate name (`[lib]` section, used in `extern crate`) to limit churn in dependent crates.

**Comment by SimonSapin** [comment]
Crates left to be updated:

servo-fontconfig = "0.2" in:
 * gfx

servo-freetype-sys = "2.4.11" in:
* azure

glx = "0.1.0" in:
* layers

servo-egl = "0.2" in:
* azure
* glutin_app
* layers

io-surface = "0.1.0" in:
* layers
* msg
